import { propertyKey } from '../helpers.ts';
import type { FileMap, Model, OpenAPIDocument, Operation, Param, SecuritySchemeObject } from '../model.ts';
import type { TypeContext } from './types.ts';
import type { ZodContext } from './zod.ts';

export const HEADER = '// Generated by api-gen-package. Do not edit by hand; re-run the generator instead.\n';

// utils/api.ts: shared axios instance. Created once, then owned by the app.
export function generateAxiosInstanceFile(baseUrl = '/'): string {
    return `import axios, { type InternalAxiosRequestConfig } from "axios";

const instance = axios.create({
    baseURL: ${JSON.stringify(baseUrl)},
});

type TokenGetter = () => string | null | undefined | Promise<string | null | undefined>;
let getAuthToken: TokenGetter | null = null;

/**
 * Register a function returning a bearer token sent with every request.
 * For the security schemes declared in your OpenAPI document, prefer setCredentials() from "./auth".
 */
export const setAuthTokenGetter = (getter: TokenGetter | null) => {
    getAuthToken = getter;
};

instance.interceptors.request.use(async (config: InternalAxiosRequestConfig) => {
    const token = await getAuthToken?.();
    if (token && !config.headers.Authorization) {
        config.headers.Authorization = \`Bearer \${token}\`;
    }
    return config;
});

// Surface the server's error message (e.g. { "message": "Email already taken" }) in error.message
instance.interceptors.response.use(undefined, (error) => {
    const data = error?.response?.data;
    const message = data?.message ?? data?.detail ?? data?.error;
    if (typeof message === "string" && message) {
        error.message = message;
    }
    return Promise.reject(error);
});

export default instance;
`;
}

// How each security scheme puts its credential on a request
function applySource(scheme: SecuritySchemeObject): string {
    const type = scheme.type;
    if (type === 'http' && /^basic$/i.test(scheme.scheme ?? '')) {
        return '(config, value) => setHeader(config, "Authorization", `Basic ${btoa(value)}`)';
    }
    if (type === 'http' || type === 'oauth2' || type === 'openIdConnect') {
        return '(config, value) => setHeader(config, "Authorization", `Bearer ${value}`)';
    }
    if (type === 'apiKey' && scheme.in === 'header') {
        return `(config, value) => setHeader(config, ${JSON.stringify(scheme.name)}, value)`;
    }
    if (type === 'apiKey' && scheme.in === 'query') {
        return `(config, value) => {
        config.params = { ...config.params, ${propertyKey(scheme.name ?? 'api_key')}: value };
    }`;
    }
    // Cookies cannot be set from browser code; send the existing ones instead
    return `(config) => {
        config.withCredentials = true;
    }`;
}

function describeScheme(name: string, scheme: SecuritySchemeObject): string {
    if (scheme.type === 'http' && /^basic$/i.test(scheme.scheme ?? '')) return `${name}: return "username:password"`;
    if (scheme.type === 'apiKey') return `${name}: return the API key (sent in ${scheme.in} "${scheme.name}")`;
    return `${name}: return the access token`;
}

// utils/auth.ts: credentials for the document's security schemes, regenerated every run
export function generateAuthFile(api: OpenAPIDocument): FileMap {
    const schemes = (api.components && api.components.securitySchemes) || {};
    const names = Object.keys(schemes);
    if (names.length === 0) return {};

    const content = `${HEADER}import type { AxiosRequestConfig } from "axios";

export type SecuritySchemeName = ${names.map(name => JSON.stringify(name)).join(' | ')};

type Credential = string | null | undefined;
type CredentialGetter = () => Credential | Promise<Credential>;

const getters: Partial<Record<SecuritySchemeName, CredentialGetter>> = {};

/**
 * Register how to obtain the credential for a security scheme, e.g. setCredentials(${JSON.stringify(names[0])}, () => localStorage.getItem("token")).
${names.map(name => ` * - ${describeScheme(name, schemes[name])}`).join('\n')}
 */
export const setCredentials = (scheme: SecuritySchemeName, getter: CredentialGetter | null) => {
    if (getter) getters[scheme] = getter;
    else delete getters[scheme];
};

function setHeader(config: AxiosRequestConfig, name: string, value: string) {
    config.headers = { ...(config.headers as Record<string, string> | undefined), [name]: value };
}

const appliers: Record<SecuritySchemeName, (config: AxiosRequestConfig, value: string) => void> = {
${names.map(name => `    ${propertyKey(name)}: ${applySource(schemes[name])},`).join('\n')}
};

/**
 * Add credentials for the first security alternative whose credentials are all registered.
 * Alternatives come from the operation's "security" requirement (OR between alternatives, AND within one).
 */
export async function withAuth(config: AxiosRequestConfig | undefined, alternatives: SecuritySchemeName[][]): Promise<AxiosRequestConfig> {
    const result: AxiosRequestConfig = { ...config };
    for (const alternative of alternatives) {
        const values = await Promise.all(alternative.map(async (scheme) => (await getters[scheme]?.()) ?? null));
        if (values.every((value) => value)) {
            alternative.forEach((scheme, index) => appliers[scheme](result, values[index] as string));
            break;
        }
    }
    return result;
}
`;
    return { 'utils/auth.ts': content };
}

function jsDoc(op: Operation): string {
    const lines = [op.summary, op.description && op.description !== op.summary ? op.description : null]
        .filter(Boolean)
        .flatMap(text => String(text).replace(/\*\//g, '*\\/').split('\n'));
    if (op.deprecated) lines.push('@deprecated');
    lines.push(`${op.method.toUpperCase()} ${op.path}`);
    return `/**\n${lines.map(line => ` * ${line}`).join('\n')}\n */\n`;
}

function paramObjectType(params: Param[], context: TypeContext, usedTypes: Set<string>): string {
    const members = params.map(param => {
        const doc = param.description ? `/** ${String(param.description).replace(/\*\//g, '*\\/')} */ ` : '';
        return `${doc}${propertyKey(param.name)}${param.required ? '' : '?'}: ${context.tsType(param.schema, usedTypes)};`;
    });
    return `{ ${members.join(' ')} }`;
}

interface Used {
    types: Set<string>;
    schemas: Set<string>;
    auth: boolean;
    zod: boolean;
    unwrap: boolean;
}

// Added to API files whose responses are wrapped, e.g. { success: true, data: {...} }
const UNWRAP_HELPER = `
/** Return the payload of a wrapped response (or the whole body), or throw the server's message when it reports a failure */
function unwrap<T>(envelope: object, key: string | null): T {
    const body = envelope as Record<string, unknown>;
    if (body.success === false || body.ok === false) {
        const message = body.message ?? body.error;
        throw new Error(typeof message === "string" && message ? message : "Request failed");
    }
    return (key === null ? body : body[key]) as T;
}`;

function generateFunction(
    op: Operation,
    { context, zodContext, schemeNames }: { context: TypeContext; zodContext: ZodContext | null; schemeNames: string[] },
    used: Used
): string {
    const args = op.pathParams.map(param => `${param.identifier}: ${context.tsType(param.schema, used.types)}`);

    if (op.body) {
        const bodyType = op.body.multipart ? 'FormData' : context.tsType(op.body.schema, used.types);
        args.push(`body: ${bodyType}${op.body.required ? '' : ' | undefined'}`);
    }
    const hasQuery = op.queryParams.length > 0;
    if (hasQuery) {
        const optional = op.queryParams.every(param => !param.required);
        args.push(`query${optional ? '?' : ''}: ${paramObjectType(op.queryParams, context, used.types)}`);
    }
    const hasHeaders = op.headerParams.length > 0;
    if (hasHeaders) {
        const optional = op.headerParams.every(param => !param.required);
        args.push(`headers${optional ? '?' : ''}: ${paramObjectType(op.headerParams, context, used.types)}`);
    }
    args.push('config?: AxiosRequestConfig');

    // What the server sends, and what the function returns (the payload when the response is an envelope)
    const bodyType = op.responseSchema ? context.tsType(op.responseSchema, used.types) : 'void';
    const responseType = op.returnSchema ? context.tsType(op.returnSchema, used.types) : 'void';
    const url = '`' + op.path.replace(/\{([^}]+)\}/g, (_match: string, name: string) => {
        const param = op.pathParams.find(p => p.name === name);
        return `\${encodeURIComponent(String(${param ? param.identifier : name}))}`;
    }) + '`';

    // Only keep alternatives made of declared schemes; an empty list means the endpoint is public
    const alternatives = op.security.filter(alternative => alternative.every(name => schemeNames.includes(name)));
    const needsAuth = alternatives.length > 0 && alternatives.some(alternative => alternative.length > 0);

    const configParts = ['...config'];
    if (hasQuery) configParts.push('params: { ...config?.params, ...query }');
    if (hasHeaders) {
        configParts.push('headers: { ...(config?.headers as Record<string, string> | undefined), ...headers }');
    }
    if (op.method === 'delete' && op.body) configParts.push('data: body');
    let requestConfig = configParts.length === 1 ? 'config' : `{ ${configParts.join(', ')} }`;
    if (needsAuth) {
        used.auth = true;
        requestConfig = `await withAuth(${requestConfig}, ${JSON.stringify(alternatives)})`;
    }

    let call: string;
    if (['post', 'put', 'patch'].includes(op.method)) {
        call = `instance.${op.method}<${bodyType}>(${url}, ${op.body ? 'body' : 'undefined'}, ${requestConfig})`;
    } else {
        call = `instance.${op.method}<${bodyType}>(${url}, ${requestConfig})`;
    }

    let result = 'data';
    if (zodContext && op.responseSchema && op.responseIsJson) {
        used.zod = true;
        const usedSchemas = new Set<string>();
        const expression = zodContext.zod(op.responseSchema, usedSchemas);
        usedSchemas.forEach(name => used.schemas.add(name));
        result = `${expression}.parse(data)`;
    }
    if (op.envelope) {
        used.unwrap = true;
        result = `unwrap<${responseType}>(${result}, ${JSON.stringify(op.envelope.key)})`;
    }

    return `${jsDoc(op)}export const ${op.functionName} = async (${args.join(', ')}): Promise<${responseType}> => {
    const { data } = await ${call};
    return ${result};
};`;
}

/**
 * api/<model>.ts per model.
 * options.zodContext: validate JSON responses with the schemas in schemas/index.ts
 */
export function generateAPIFiles(
    models: Model[],
    context: TypeContext,
    api: OpenAPIDocument,
    { zodContext = null }: { zodContext?: ZodContext | null } = {}
): FileMap {
    const schemeNames = Object.keys((api.components && api.components.securitySchemes) || {});
    const files: FileMap = {};
    for (const model of models) {
        const used: Used = { types: new Set(), schemas: new Set(), auth: false, zod: false, unwrap: false };
        const functions = model.operations.map(op => generateFunction(op, { context, zodContext, schemeNames }, used));

        const imports = ['import type { AxiosRequestConfig } from "axios";'];
        if (used.zod) imports.push('import { z } from "zod";');
        imports.push('import instance from "../utils/api";');
        if (used.auth) imports.push('import { withAuth } from "../utils/auth";');
        if (used.types.size > 0) imports.push(`import type { ${[...used.types].sort().join(', ')} } from "../types";`);
        if (used.schemas.size > 0) {
            imports.push(`import { ${[...used.schemas].sort().map(name => `${name}Schema`).join(', ')} } from "../schemas";`);
        }

        files[`api/${model.name}.ts`] = `${HEADER}${imports.join('\n')}
${used.unwrap ? UNWRAP_HELPER + '\n' : ''}
${functions.join('\n\n')}
`;
    }
    return files;
}

