import { propertyKey } from '../helpers.ts';
import type { FileMap, OpenAPIDocument, SchemaObject } from '../model.ts';
import type { TypeContext } from './types.ts';

const HEADER = '// Generated by api-gen-package. Do not edit by hand; re-run the generator instead.\n';

export interface ZodContext {
    /** Zod expression for a schema; referenced schema type names are added to `used` */
    zod(schema: SchemaObject | null | undefined, used?: Set<string>): string;
}

// Zod expressions mirroring the TypeScript types, for runtime response validation
export function createZodContext(typeContext: TypeContext): ZodContext {
    const union = (options: string[]) => (options.length === 1 ? options[0] : `z.union([${options.join(', ')}])`);

    function zod(schema: SchemaObject | null | undefined, used: Set<string> = new Set()): string {
        if (!schema) return 'z.unknown()';
        if (schema.$ref) {
            const name = typeContext.refTypeName(schema.$ref);
            if (name) {
                used.add(name);
                // Lazy so schemas can reference each other (and themselves) in any order
                return `z.lazy(() => ${name}Schema)`;
            }
            return zod(typeContext.deref(schema), used);
        }

        let expression: string;
        let nullable = !!schema.nullable;

        if (schema.const !== undefined) {
            expression = `z.literal(${JSON.stringify(schema.const)})`;
        } else if (schema.enum) {
            const values = schema.enum.filter(value => value !== null);
            if (values.length < schema.enum.length) nullable = true;
            expression = values.every(value => typeof value === 'string')
                ? `z.enum([${values.map(value => JSON.stringify(value)).join(', ')}])`
                : union(values.map(value => `z.literal(${JSON.stringify(value)})`));
        } else if (schema.allOf) {
            expression = schema.allOf.map(part => zod(part, used)).reduce((left, right) => `z.intersection(${left}, ${right})`);
        } else if (schema.oneOf || schema.anyOf) {
            expression = union((schema.oneOf || schema.anyOf || []).map(part => zod(part, used)));
        } else {
            let types: Array<string | undefined> = Array.isArray(schema.type) ? schema.type : [schema.type];
            if (types.includes('null')) {
                nullable = true;
                types = types.filter(t => t !== 'null');
            }
            expression = types.length === 0 ? 'z.null()' : union(types.map(type => scalar(schema, type, used)));
        }

        return nullable && expression !== 'z.null()' ? `${expression}.nullable()` : expression;
    }

    function scalar(schema: SchemaObject, type: string | undefined, used: Set<string>): string {
        switch (type) {
            case 'integer':
            case 'number':
                return 'z.number()';
            case 'boolean':
                return 'z.boolean()';
            case 'string':
                return schema.format === 'binary' ? 'z.instanceof(Blob)' : 'z.string()';
            case 'array':
                return `z.array(${zod(schema.items, used)})`;
            case 'object':
                return object(schema, used);
            default:
                return schema.properties || schema.additionalProperties ? object(schema, used) : 'z.unknown()';
        }
    }

    function object(schema: SchemaObject, used: Set<string>): string {
        const required = schema.required ?? [];
        const entries = Object.entries(schema.properties ?? {});
        const valueSchema =
            schema.additionalProperties && schema.additionalProperties !== true ? zod(schema.additionalProperties, used) : 'z.unknown()';
        if (entries.length === 0) return `z.record(z.string(), ${valueSchema})`;
        const members = entries.map(
            ([name, prop]) => `${propertyKey(name)}: ${zod(prop, used)}${required.includes(name) ? '' : '.optional()'}`
        );
        // Unknown extra properties from the server are kept, not rejected
        return `z.object({ ${members.join(', ')} }).passthrough()`;
    }

    return { zod };
}

// schemas/index.ts: one zod schema per component schema, typed against types/index.ts
export function generateZodSchemas(api: OpenAPIDocument, typeContext: TypeContext, zodContext: ZodContext): FileMap {
    const schemas = api.components?.schemas ?? {};
    const declarations = Object.entries(schemas).map(([name, schema]) => {
        const typeName = typeContext.typeNames[name];
        return `export const ${typeName}Schema: z.ZodType<T.${typeName}> = ${zodContext.zod(schema)};`;
    });
    const typesImport = declarations.length > 0 ? 'import type * as T from "../types";\n' : '';
    return {
        'schemas/index.ts': `${HEADER}import { z } from "zod";\n${typesImport}\n${declarations.join('\n\n') || 'export {};'}\n`,
    };
}
