const { propertyKey } = require('../utils/helpers');

const HEADER = '// Generated by api-gen-package. Do not edit by hand; re-run the generator instead.\n';

// utils/api.ts: shared axios instance with auth and error-message interceptors
function generateAxiosInstanceFile(baseUrl = '/') {
    return `import axios, { type InternalAxiosRequestConfig } from "axios";

const instance = axios.create({
    baseURL: ${JSON.stringify(baseUrl)},
});

type TokenGetter = () => string | null | undefined | Promise<string | null | undefined>;
let getAuthToken: TokenGetter | null = null;

/** Register a function returning the current auth token; it is sent as "Authorization: Bearer <token>". */
export const setAuthTokenGetter = (getter: TokenGetter | null) => {
    getAuthToken = getter;
};

instance.interceptors.request.use(async (config: InternalAxiosRequestConfig) => {
    const token = await getAuthToken?.();
    if (token) {
        config.headers.Authorization = \`Bearer \${token}\`;
    }
    return config;
});

// Surface the server's error message (e.g. { "message": "Email already taken" }) in error.message
instance.interceptors.response.use(undefined, (error) => {
    const data = error?.response?.data;
    const message = data?.message ?? data?.detail ?? data?.error;
    if (typeof message === "string" && message) {
        error.message = message;
    }
    return Promise.reject(error);
});

export default instance;
`;
}

function jsDoc(op) {
    const lines = [op.summary, op.description && op.description !== op.summary ? op.description : null]
        .filter(Boolean)
        .flatMap(text => String(text).replace(/\*\//g, '*\\/').split('\n'));
    if (op.deprecated) lines.push('@deprecated');
    lines.push(`${op.method.toUpperCase()} ${op.path}`);
    return `/**\n${lines.map(line => ` * ${line}`).join('\n')}\n */\n`;
}

function generateFunction(op, context, usedTypes) {
    const args = op.pathParams.map(param => `${param.identifier}: ${context.tsType(param.schema, usedTypes)}`);

    if (op.body) {
        const bodyType = /multipart\/form-data/i.test(op.body.contentType) ? 'FormData' : context.tsType(op.body.schema, usedTypes);
        args.push(`body: ${bodyType}${op.body.required ? '' : ' | undefined'}`);
    }

    const hasQuery = op.queryParams.length > 0;
    if (hasQuery) {
        const members = op.queryParams.map(param => {
            const doc = param.description ? `/** ${String(param.description).replace(/\*\//g, '*\\/')} */ ` : '';
            return `${doc}${propertyKey(param.name)}${param.required ? '' : '?'}: ${context.tsType(param.schema, usedTypes)};`;
        });
        const optional = op.queryParams.every(param => !param.required);
        args.push(`query${optional ? '?' : ''}: { ${members.join(' ')} }`);
    }
    args.push('config?: AxiosRequestConfig');

    const responseType = op.responseSchema ? context.tsType(op.responseSchema, usedTypes) : 'void';
    const url = '`' + op.path.replace(/\{([^}]+)\}/g, (match, name) => {
        const param = op.pathParams.find(p => p.name === name);
        return `\${encodeURIComponent(String(${param ? param.identifier : name}))}`;
    }) + '`';
    const requestConfig = hasQuery ? '{ ...config, params: query }' : 'config';

    let call;
    if (['post', 'put', 'patch'].includes(op.method)) {
        call = `instance.${op.method}<${responseType}>(${url}, ${op.body ? 'body' : 'undefined'}, ${requestConfig})`;
    } else if (op.method === 'delete' && op.body) {
        call = `instance.delete<${responseType}>(${url}, { ...config, ${hasQuery ? 'params: query, ' : ''}data: body })`;
    } else {
        call = `instance.${op.method}<${responseType}>(${url}, ${requestConfig})`;
    }

    return `${jsDoc(op)}export const ${op.functionName} = async (${args.join(', ')}): Promise<${responseType}> => {
    const { data } = await ${call};
    return data;
};`;
}

// api/<model>.ts per model
function generateAPIFiles(models, context) {
    const files = {};
    for (const model of models) {
        const usedTypes = new Set();
        const functions = model.operations.map(op => generateFunction(op, context, usedTypes));
        const typeImport = usedTypes.size > 0 ? `import type { ${[...usedTypes].sort().join(', ')} } from "../types";\n` : '';

        files[`api/${model.name}.ts`] = `${HEADER}import type { AxiosRequestConfig } from "axios";
import instance from "../utils/api";
${typeImport}
${functions.join('\n\n')}
`;
    }
    return files;
}

module.exports = {
    generateAxiosInstanceFile,
    generateAPIFiles,
    HEADER,
};
