import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { loadSpec, buildModels } from './spec.ts';
import { createTypeContext, generateTypes } from './generators/types.ts';
import { createZodContext, generateZodSchemas, type ZodContext } from './generators/zod.ts';
import { generateAxiosInstanceFile, generateAuthFile, generateAPIFiles } from './generators/api.ts';
import { generateReactQueryHooks } from './generators/hooks.ts';
import { generateCRUDDashboard, ROUTERS } from './generators/dashboard.ts';
import { applyTemplate } from './helpers.ts';
import { applyResourceOptions, resolveUi, type UiOptions } from './ui.ts';
import type { FileMap, OpenAPIDocument, RouterName, Target, TemplateKind, Templates } from './model.ts';

export const TARGETS: Target[] = ['api', 'hooks', 'dashboard'];
const MANIFEST = '.api-gen-manifest.json';
const GENERATED_MARKER = 'Generated by api-gen-package';
const CONFIG_FILES = ['api-gen.config.json', 'api-gen.config.js', 'api-gen.config.mjs', 'api-gen.config.cjs'];

export interface GenerateOptions {
    /** Path or URL of the OpenAPI 3 / Swagger 2 document (YAML or JSON) */
    input: string;
    /** Output directory (default "./src") */
    output?: string;
    /** Subset of "api", "hooks", "dashboard" (default: all) */
    only?: Target[];
    /** Dashboard routing (default "react-router") */
    router?: RouterName;
    /** axios baseURL for a newly created utils/api.ts (default: the document's first server URL, else "/") */
    baseUrl?: string;
    /** Path prefix before the resource name (default: auto-detect /api, /v1, ...) */
    prefix?: string;
    /** Group operations into resources by first path segment or by first tag (default "path") */
    groupBy?: 'path' | 'tag';
    /**
     * Wrapped responses such as { success, data }: by default detected automatically and unwrapped for single
     * records. A property name forces that payload key; false turns unwrapping off.
     */
    envelope?: string | false;
    /** Dashboard look and wording: title, locale, labels, page size, theme colors, per-resource labels */
    ui?: UiOptions;
    /** Generate a login page when the API has a sign-in endpoint (default true) */
    login?: boolean;
    /** Validate JSON responses at runtime with generated zod schemas */
    zod?: boolean;
    /** Template overrides, or a path to a module exporting them */
    templates?: Templates | string | null;
    /** Delete files generated by a previous run that are no longer produced (default true) */
    clean?: boolean;
    /** Format output with Prettier (default true) */
    format?: boolean;
}

export interface GenerateResult {
    written: string[];
    removed: string[];
    skipped: string[];
    warnings: string[];
}

async function formatFile(filePath: string, content: string): Promise<string> {
    const prettier = await import('prettier');
    const config = (await prettier.resolveConfig(filePath)) || { tabWidth: 4, printWidth: 120 };
    try {
        return await prettier.format(content, { ...config, filepath: filePath });
    } catch (error) {
        throw new Error(`Generated invalid code in ${filePath}: ${(error as Error).message}`);
    }
}

async function importModule(file: string): Promise<Record<string, unknown>> {
    const module = await import(pathToFileURL(path.resolve(file)).href);
    return (module.default ?? module) as Record<string, unknown>;
}

/**
 * Read options from a config file. Without an explicit path, looks for api-gen.config.{json,js,mjs,cjs} in `cwd`.
 * Relative paths inside the file (input, output, templates) are resolved against the file's folder.
 */
export async function loadConfig(configPath?: string, cwd = process.cwd()): Promise<Partial<GenerateOptions>> {
    let file = configPath ? path.resolve(cwd, configPath) : null;
    if (!file) {
        file = CONFIG_FILES.map(name => path.join(cwd, name)).find(candidate => fs.existsSync(candidate)) ?? null;
        if (!file) return {};
    }
    if (!fs.existsSync(file)) throw new Error(`Config file not found: ${file}`);

    const config = (file.endsWith('.json') ? JSON.parse(fs.readFileSync(file, 'utf8')) : await importModule(file)) as Partial<GenerateOptions>;
    const dir = path.dirname(file);
    const resolveLocal = (value: string) => (/^https?:\/\//i.test(value) ? value : path.resolve(dir, value));
    return {
        ...config,
        ...(typeof config.input === 'string' && { input: resolveLocal(config.input) }),
        ...(typeof config.output === 'string' && { output: resolveLocal(config.output) }),
        ...(typeof config.templates === 'string' && { templates: resolveLocal(config.templates) }),
    };
}

async function loadTemplates(templates: GenerateOptions['templates']): Promise<Templates | null> {
    if (!templates) return null;
    if (typeof templates === 'string') return (await importModule(templates)) as Templates;
    return templates;
}

// The first server URL with its variables filled in, e.g. https://{region}.example.com -> https://eu.example.com
function serverUrl(api: OpenAPIDocument): string | null {
    const server = api.servers?.[0];
    if (!server?.url) return null;
    return server.url.replace(/\{([^}]+)\}/g, (match, name: string) => server.variables?.[name]?.default ?? match);
}

const targetOf = (file: string): Target => (/^hooks\//.test(file) ? 'hooks' : /^(pages|app|components)\//.test(file) ? 'dashboard' : 'api');

function readManifest(output: string): string[] {
    try {
        return JSON.parse(fs.readFileSync(path.join(output, MANIFEST), 'utf8')).files || [];
    } catch {
        return [];
    }
}

// Delete files a previous run generated that this run did not, if they still carry the generated marker
function removeStaleFiles(output: string, previous: string[], current: string[]): string[] {
    const removed: string[] = [];
    const keep = new Set(current);
    const root = path.resolve(output);
    for (const relativePath of previous) {
        if (keep.has(relativePath)) continue;
        const filePath = path.join(root, relativePath);
        if (!fs.existsSync(filePath) || !fs.readFileSync(filePath, 'utf8').includes(GENERATED_MARKER)) continue;
        fs.unlinkSync(filePath);
        removed.push(relativePath);

        // Remove folders left empty, up to the output directory
        let dir = path.dirname(filePath);
        while (dir.startsWith(root) && dir !== root && fs.readdirSync(dir).length === 0) {
            fs.rmdirSync(dir);
            dir = path.dirname(dir);
        }
    }
    return removed;
}

/**
 * Generate the API client, React Query hooks and shadcn/ui dashboard from an OpenAPI document.
 */
export async function generate(options: GenerateOptions): Promise<GenerateResult> {
    const {
        input,
        output = './src',
        only = TARGETS,
        router = 'react-router',
        prefix,
        groupBy = 'path',
        zod = false,
        clean = true,
        format = true,
    } = options;

    if (!input) throw new Error('An input OpenAPI document is required.');
    const unknownTargets = only.filter(target => !TARGETS.includes(target));
    if (unknownTargets.length > 0) {
        throw new Error(`Unknown target(s) ${unknownTargets.join(', ')}. Use: ${TARGETS.join(', ')}`);
    }
    if (!ROUTERS[router]) throw new Error(`Unknown router "${router}". Use: ${Object.keys(ROUTERS).join(', ')}`);
    if (!['path', 'tag'].includes(groupBy)) throw new Error(`Unknown groupBy "${groupBy}". Use: path, tag`);
    const templates = await loadTemplates(options.templates);

    const api = await loadSpec(input);
    const context = createTypeContext(api);
    const ui = resolveUi(options.ui, api.info?.title);
    const built = buildModels(api, context, { prefix, groupBy, envelope: options.envelope });
    const models = applyResourceOptions(built.models, ui);
    const { skipped } = built;
    const login = options.login === false ? null : built.login && { ...built.login, model: models.find(m => m.key === built.login!.model.key) ?? built.login.model };
    // The signed-in token goes with the bearer-style security schemes
    const bearerSchemes = Object.entries(api.components?.securitySchemes ?? {})
        .filter(([, scheme]) => (scheme.type === 'http' && /^bearer$/i.test(scheme.scheme ?? '')) || scheme.type === 'oauth2' || scheme.type === 'openIdConnect')
        .map(([name]) => name);
    if (models.length === 0) {
        throw new Error(prefix !== undefined ? `No paths start with the prefix "${prefix}".` : 'No operations found in the document.');
    }

    const baseUrl = options.baseUrl ?? serverUrl(api) ?? '/';
    const files: FileMap = {};
    const warnings = skipped.map(operation => `Skipped ${operation}: no resource segment after the prefix.`);
    const addPerModel = (kind: TemplateKind, generated: FileMap) => {
        for (const [file, content] of Object.entries(generated)) {
            const model = models.find(m => file.endsWith(`/${m.name}.ts`) || file.endsWith(`/use${m.Plural}.ts`)) ?? null;
            files[file] = applyTemplate(templates, kind, content, { model, router });
        }
    };

    if (only.includes('api')) {
        Object.assign(files, generateTypes(api, context), generateAuthFile(api));
        let zodContext: ZodContext | null = null;
        if (zod) {
            zodContext = createZodContext(context);
            Object.assign(files, generateZodSchemas(api, context, zodContext));
        }
        addPerModel('api', generateAPIFiles(models, context, api, { zodContext }));

        // utils/api.ts is meant to be customized (interceptors, headers), so it is only created once
        if (fs.existsSync(path.join(output, 'utils/api.ts'))) {
            if (options.baseUrl !== undefined) {
                warnings.push('utils/api.ts already exists and was left untouched; update its baseURL by hand.');
            }
        } else {
            files['utils/api.ts'] = generateAxiosInstanceFile(baseUrl);
        }
    }
    if (only.includes('hooks')) {
        addPerModel('hooks', generateReactQueryHooks(models, ui));
    }
    if (only.includes('dashboard')) {
        const dashboard = generateCRUDDashboard(models, { router, templates, ui, login, bearerSchemes });
        Object.assign(files, dashboard.files);
        warnings.push(...dashboard.warnings);
    }

    const written: string[] = [];
    for (const [relativePath, content] of Object.entries(files)) {
        const filePath = path.join(output, relativePath);
        const finalContent = format ? await formatFile(filePath, content) : content;
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        fs.writeFileSync(filePath, finalContent);
        written.push(relativePath);
    }

    // Only files of the targets generated this run can be stale; a --only run leaves the others alone
    const previous = readManifest(output);
    const ownedByRun = (file: string) => only.includes(targetOf(file));
    const generatedFiles = written.filter(file => file !== 'utils/api.ts');
    const removed = clean ? removeStaleFiles(output, previous.filter(ownedByRun), written) : [];
    const manifestFiles = new Set([
        ...previous.filter(file => !ownedByRun(file) || (!clean && !generatedFiles.includes(file))),
        ...generatedFiles,
    ]);
    fs.writeFileSync(
        path.join(output, MANIFEST),
        JSON.stringify({ generator: 'api-gen-package', files: [...manifestFiles].sort() }, null, 2) + '\n'
    );

    return { written, removed, skipped, warnings };
}

/**
 * Generate once, then again whenever the input file changes. Returns a function that stops watching.
 */
export function watch(
    options: GenerateOptions,
    { onResult = () => {}, onError = () => {} }: { onResult?: (result: GenerateResult) => void; onError?: (error: Error) => void } = {}
): () => void {
    if (/^https?:\/\//i.test(options.input)) {
        throw new Error('--watch needs a local file, not a URL.');
    }

    let running: Promise<void> = Promise.resolve();
    const run = () => {
        running = running.then(() => generate(options).then(onResult, onError));
        return running;
    };

    run();
    // Polling survives editors that save by replacing the file, which breaks fs.watch
    const listener = (current: fs.Stats, previous: fs.Stats) => {
        if (current.mtimeMs !== previous.mtimeMs) run();
    };
    fs.watchFile(options.input, { interval: 300 }, listener);

    return () => fs.unwatchFile(options.input, listener);
}
